#! /bin/sh

### BEGIN INIT INFO
# Provides:          dlogger
# Required-Start:    $local_fs $remote_fs
# Required-Stop:
# X-Start-Before:    rmnologin
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Provided data logger functionality
# Description: Provided data logger functionality
### END INIT INFO

. /lib/lsb/init-functions

set -e

case "$1" in
  start)
	/KWH/pulse/pulseStart.sh &
        /KWH/boot/stopTXandSetTime.sh &
	;;
  stop|reload|restart|force-reload|status)
	;;
  *)
	echo "Usage: {start|stop|restart|force-reload|status}" >&2
	exit 1
	;;
esac

exit 0
