#! /bin/sh
### BEGIN INIT INFO
# Provides:          datalogger
# Required-Start:    $all
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Runs data logger functionality
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin

. /lib/init/vars.sh
. /lib/lsb/init-functions

case "$1" in
  start)
    log_begin_msg "Starting datalogger service"
    /usr/lib/pigpio/PIGPIO/pigpiod
    log_end_msg $?
    exit 0
    ;;
  stop)
    log_begin_msg "Stopping data logger service"
    killall pigpiod
    log_end_msg $?
    exit 0
    ;;
  *)
    echo "Usage: /etc/init.d/datalogger {start|stop|status}"
    exit 1
    ;;
esac
