#!/usr/bin/env python
from __future__ import print_function
import wiringpi
from time import sleep

#config
io = wiringpi.GPIO(wiringpi.GPIO.WPI_MODE_PINS)
MISO = 13
MOSI = 12
TxEnable = 2
baud_interval = 0.0001395
frame_delay = 0.014583333333333334
io.pinMode(TxEnable,io.OUTPUT)
io.pinMode(MOSI,io.OUTPUT)
io.pinMode(MISO,io.INPUT)

#prep MOSI LOW
io.digitalWrite(MOSI,io.LOW)

#create rising edge and send ":" to signal tx
io.digitalWrite(TxEnable,io.LOW)
sleep(0.1)
io.digitalWrite(TxEnable,io.HIGH)
sleep(frame_delay)

#WRITE
#byte 1 - Address
io.digitalWrite(MOSI,io.HIGH)
sleep(baud_interval)
io.digitalWrite(MOSI,io.HIGH)
sleep(baud_interval)
io.digitalWrite(MOSI,io.LOW)     
sleep(baud_interval)
io.digitalWrite(MOSI,io.LOW)     
sleep(baud_interval)
io.digitalWrite(MOSI,io.LOW)     
sleep(baud_interval)
io.digitalWrite(MOSI,io.LOW)     
sleep(baud_interval)
io.digitalWrite(MOSI,io.LOW)     
sleep(baud_interval)
io.digitalWrite(MOSI,io.LOW)     
sleep(baud_interval)
io.digitalWrite(MOSI,io.LOW)     
sleep(baud_interval)

#byte 2 - Function Code
io.digitalWrite(MOSI,io.LOW)
sleep(baud_interval)
io.digitalWrite(MOSI,io.LOW)     
sleep(baud_interval)
io.digitalWrite(MOSI,io.LOW)     
sleep(baud_interval)
io.digitalWrite(MOSI,io.LOW)     
sleep(baud_interval)
io.digitalWrite(MOSI,io.LOW)     
sleep(baud_interval)
io.digitalWrite(MOSI,io.HIGH)     
sleep(baud_interval)
io.digitalWrite(MOSI,io.LOW)     
sleep(baud_interval)
io.digitalWrite(MOSI,io.LOW)     
sleep(baud_interval)

#byte 3 - Start Address HIGH
io.digitalWrite(MOSI,io.LOW)
sleep(baud_interval)
io.digitalWrite(MOSI,io.LOW)     
sleep(baud_interval)
io.digitalWrite(MOSI,io.LOW)     
sleep(baud_interval)
io.digitalWrite(MOSI,io.LOW)     
sleep(baud_interval)
io.digitalWrite(MOSI,io.LOW)     
sleep(baud_interval)
io.digitalWrite(MOSI,io.LOW)     
sleep(baud_interval)
io.digitalWrite(MOSI,io.LOW)     
sleep(baud_interval)
io.digitalWrite(MOSI,io.LOW)     
sleep(baud_interval)

#byte 4 - Start Address LOW
io.digitalWrite(MOSI,io.LOW)
sleep(baud_interval)
io.digitalWrite(MOSI,io.LOW)     
sleep(baud_interval)
io.digitalWrite(MOSI,io.LOW)     
sleep(baud_interval)
io.digitalWrite(MOSI,io.LOW)     
sleep(baud_interval)
io.digitalWrite(MOSI,io.LOW)     
sleep(baud_interval)
io.digitalWrite(MOSI,io.LOW)     
sleep(baud_interval)
io.digitalWrite(MOSI,io.LOW)     
sleep(baud_interval)
io.digitalWrite(MOSI,io.LOW)     
sleep(baud_interval)

#byte 5 - Number of registers HIGH
io.digitalWrite(MOSI,io.LOW)
sleep(baud_interval)
io.digitalWrite(MOSI,io.LOW)     
sleep(baud_interval)
io.digitalWrite(MOSI,io.LOW)     
sleep(baud_interval)
io.digitalWrite(MOSI,io.LOW)     
sleep(baud_interval)
io.digitalWrite(MOSI,io.LOW)     
sleep(baud_interval)
io.digitalWrite(MOSI,io.LOW)     
sleep(baud_interval)
io.digitalWrite(MOSI,io.LOW)     
sleep(baud_interval)
io.digitalWrite(MOSI,io.LOW)     
sleep(baud_interval)

#byte 6 - Number of registers LOW
io.digitalWrite(MOSI,io.LOW)
sleep(baud_interval)
io.digitalWrite(MOSI,io.LOW)     
sleep(baud_interval)
io.digitalWrite(MOSI,io.LOW)     
sleep(baud_interval)
io.digitalWrite(MOSI,io.LOW)     
sleep(baud_interval)
io.digitalWrite(MOSI,io.LOW)     
sleep(baud_interval)
io.digitalWrite(MOSI,io.LOW)     
sleep(baud_interval)
io.digitalWrite(MOSI,io.HIGH)     
sleep(baud_interval)
io.digitalWrite(MOSI,io.LOW)     
sleep(baud_interval)

#byte 7 - Error Check LOW
io.digitalWrite(MOSI,io.LOW)
sleep(baud_interval)
io.digitalWrite(MOSI,io.HIGH)     
sleep(baud_interval)
io.digitalWrite(MOSI,io.HIGH)     
sleep(baud_interval)
io.digitalWrite(MOSI,io.HIGH)     
sleep(baud_interval)
io.digitalWrite(MOSI,io.LOW)     
sleep(baud_interval)
io.digitalWrite(MOSI,io.LOW)     
sleep(baud_interval)
io.digitalWrite(MOSI,io.LOW)     
sleep(baud_interval)
io.digitalWrite(MOSI,io.HIGH)     
sleep(baud_interval)

#byte 8 - Error Check HIGH
io.digitalWrite(MOSI,io.HIGH)
sleep(baud_interval)
io.digitalWrite(MOSI,io.HIGH)     
sleep(baud_interval)
io.digitalWrite(MOSI,io.LOW)     
sleep(baud_interval)
io.digitalWrite(MOSI,io.LOW)     
sleep(baud_interval)
io.digitalWrite(MOSI,io.HIGH)     
sleep(baud_interval)
io.digitalWrite(MOSI,io.LOW)     
sleep(baud_interval)
io.digitalWrite(MOSI,io.HIGH)     
sleep(baud_interval)
io.digitalWrite(MOSI,io.HIGH)     
sleep(baud_interval)

     
#Switch to read mode

sleep(frame_delay)
io.digitalWrite(TxEnable,io.LOW)

#READ
#byte 1
print(io.digitalRead(MISO), end="")
sleep(baud_interval)
print(io.digitalRead(MISO), end="")
sleep(baud_interval)
print(io.digitalRead(MISO), end="")
sleep(baud_interval)
print(io.digitalRead(MISO), end="")
sleep(baud_interval)
print(io.digitalRead(MISO), end="")
sleep(baud_interval)
print(io.digitalRead(MISO), end="")
sleep(baud_interval)
print(io.digitalRead(MISO), end="")
sleep(baud_interval)
print(io.digitalRead(MISO), end="")
sleep(baud_interval)
print(" ", end=" ")

#byte 2
print(io.digitalRead(MISO), end="")
sleep(baud_interval)
print(io.digitalRead(MISO), end="")
sleep(baud_interval)
print(io.digitalRead(MISO), end="")
sleep(baud_interval)
print(io.digitalRead(MISO), end="")
sleep(baud_interval)
print(io.digitalRead(MISO), end="")
sleep(baud_interval)
print(io.digitalRead(MISO), end="")
sleep(baud_interval)
print(io.digitalRead(MISO), end="")
sleep(baud_interval)
print(io.digitalRead(MISO), end="")
sleep(baud_interval)
print(" ", end=" ")

#byte 3
print(io.digitalRead(MISO), end="")
sleep(baud_interval)
print(io.digitalRead(MISO), end="")
sleep(baud_interval)
print(io.digitalRead(MISO), end="")
sleep(baud_interval)
print(io.digitalRead(MISO), end="")
sleep(baud_interval)
print(io.digitalRead(MISO), end="")
sleep(baud_interval)
print(io.digitalRead(MISO), end="")
sleep(baud_interval)
print(io.digitalRead(MISO), end="")
sleep(baud_interval)
print(io.digitalRead(MISO), end="")
sleep(baud_interval)
print(" ", end=" ")

#byte 4
print(io.digitalRead(MISO), end="")
sleep(baud_interval)
print(io.digitalRead(MISO), end="")
sleep(baud_interval)
print(io.digitalRead(MISO), end="")
sleep(baud_interval)
print(io.digitalRead(MISO), end="")
sleep(baud_interval)
print(io.digitalRead(MISO), end="")
sleep(baud_interval)
print(io.digitalRead(MISO), end="")
sleep(baud_interval)
print(io.digitalRead(MISO), end="")
sleep(baud_interval)
print(io.digitalRead(MISO), end="")
sleep(baud_interval)
print(" ", end=" ")

#byte 5
print(io.digitalRead(MISO), end="")
sleep(baud_interval)
print(io.digitalRead(MISO), end="")
sleep(baud_interval)
print(io.digitalRead(MISO), end="")
sleep(baud_interval)
print(io.digitalRead(MISO), end="")
sleep(baud_interval)
print(io.digitalRead(MISO), end="")
sleep(baud_interval)
print(io.digitalRead(MISO), end="")
sleep(baud_interval)
print(io.digitalRead(MISO), end="")
sleep(baud_interval)
print(io.digitalRead(MISO), end="")
sleep(baud_interval)
print(" ", end=" ")

#byte 6
print(io.digitalRead(MISO), end="")
sleep(baud_interval)
print(io.digitalRead(MISO), end="")
sleep(baud_interval)
print(io.digitalRead(MISO), end="")
sleep(baud_interval)
print(io.digitalRead(MISO), end="")
sleep(baud_interval)
print(io.digitalRead(MISO), end="")
sleep(baud_interval)
print(io.digitalRead(MISO), end="")
sleep(baud_interval)
print(io.digitalRead(MISO), end="")
sleep(baud_interval)
print(io.digitalRead(MISO), end="")
sleep(baud_interval)
print(" ", end=" ")

#byte 7
print(io.digitalRead(MISO), end="")
sleep(baud_interval)
print(io.digitalRead(MISO), end="")
sleep(baud_interval)
print(io.digitalRead(MISO), end="")
sleep(baud_interval)
print(io.digitalRead(MISO), end="")
sleep(baud_interval)
print(io.digitalRead(MISO), end="")
sleep(baud_interval)
print(io.digitalRead(MISO), end="")
sleep(baud_interval)
print(io.digitalRead(MISO), end="")
sleep(baud_interval)
print(io.digitalRead(MISO), end="")
sleep(baud_interval)
print(" ", end=" ")

#byte 8
print(io.digitalRead(MISO), end="")
sleep(baud_interval)
print(io.digitalRead(MISO), end="")
sleep(baud_interval)
print(io.digitalRead(MISO), end="")
sleep(baud_interval)
print(io.digitalRead(MISO), end="")
sleep(baud_interval)
print(io.digitalRead(MISO), end="")
sleep(baud_interval)
print(io.digitalRead(MISO), end="")
sleep(baud_interval)
print(io.digitalRead(MISO), end="")
sleep(baud_interval)
print(io.digitalRead(MISO), end="")
sleep(baud_interval)
print(" ")
